from enum import Enum


class ActionEnum(Enum):
    QUADRANT_CHECK = 0
    QUADRANT_CLEANING = 1
    QUADRANT_CHANGE = 2
    QUADRANT_CLEANING_CHANGE = 3
    QUADRANT_CHECK_FOR_PAUSE = 4
    QUADRANT_CLEANING_PAUSE = 5
    QUADRANT_PAUSE = 6
