from enum import Enum


class StateEnum(Enum):
    QUADRANT_CHECKED = 0
    QUADRANT_CLEANED = 1
    QUADRANT_CHANGED = 2
    QUADRANT_CLEANED_CHANGED = 3
    QUADRANT_CHECKED_FOR_PAUSE = 4
    QUADRANT_CLEANED_PAUSED = 5
    QUADRANT_PAUSED = 6

